name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        with:
          cli: 1.11.3.1463
          bb: 1.3.191
          clj-kondo: 2024.08.01
          cljfmt: 0.12.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Echo versions
        run: |
          node --version
          npm --version
          clojure --version
          bb --version
          clj-kondo --version
          cljfmt --version

      - name: Configure and build
        run: |
          npm ci
          bb config
          bb kidney
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: resources/public

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: resources/public
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './resources/public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          production-deploy: ${{ env.BRANCH_NAME }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        timeout-minutes: 1