name: PR

on:
  pull_request:
    branches:
      - develop
      - main
      - main-patch
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.5
        if: github.event.action != 'closed'
        with:
          cli: 1.11.3.1463
          bb: 1.3.191
          clj-kondo: 2024.08.01
          cljfmt: 0.12.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check tag format
        if: github.base_ref == 'main'
        run: |
          sh validate_tag.sh

      - name: Echo versions
        if: github.event.action != 'closed'
        run: |
          node --version
          npm --version
          clojure --version
          bb --version
          clj-kondo --version
          cljfmt --version

      - name: Configure and build
        if: github.event.action != 'closed'
        run: |
          npm ci
          bb config
          bb kidney
          npm run build
          sh build_number.sh

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./resources/public